// Generated by CIRCT firtool-1.75.0
module GCD(	// @[src/main/scala/GCD.scala:7:7]
  input         clock,	// @[src/main/scala/GCD.scala:7:7]
  input         reset,	// @[src/main/scala/GCD.scala:7:7]
  input  [15:0] io_value1,	// @[src/main/scala/GCD.scala:8:14]
  input  [15:0] io_value2,	// @[src/main/scala/GCD.scala:8:14]
  input         io_loadingValues,	// @[src/main/scala/GCD.scala:8:14]
  output [15:0] io_outputGCD,	// @[src/main/scala/GCD.scala:8:14]
  output        io_outputValid	// @[src/main/scala/GCD.scala:8:14]
);

  reg [15:0] x;	// @[src/main/scala/GCD.scala:16:15]
  reg [15:0] y;	// @[src/main/scala/GCD.scala:17:15]
  always @(posedge clock) begin	// @[src/main/scala/GCD.scala:7:7]
    if (io_loadingValues) begin	// @[src/main/scala/GCD.scala:8:14]
      x <= io_value1;	// @[src/main/scala/GCD.scala:16:15]
      y <= io_value2;	// @[src/main/scala/GCD.scala:17:15]
    end
    else if (x > y)	// @[src/main/scala/GCD.scala:16:15, :17:15, :19:10]
      x <= x - y;	// @[src/main/scala/GCD.scala:16:15, :17:15, :19:24]
    else	// @[src/main/scala/GCD.scala:19:10]
      y <= y - x;	// @[src/main/scala/GCD.scala:16:15, :17:15, :20:25]
  end // always @(posedge)
  assign io_outputGCD = x;	// @[src/main/scala/GCD.scala:7:7, :16:15]
  assign io_outputValid = y == 16'h0;	// @[src/main/scala/GCD.scala:7:7, :17:15, :28:23]
endmodule

