// Generated by CIRCT firtool-1.75.0
module Fir(	// @[src/main/scala/Fir.scala:7:7]
  input        clock,	// @[src/main/scala/Fir.scala:7:7]
  input        reset,	// @[src/main/scala/Fir.scala:7:7]
  input  [3:0] io_in,	// @[src/main/scala/Fir.scala:8:14]
  input        io_valid,	// @[src/main/scala/Fir.scala:8:14]
  output [3:0] io_out,	// @[src/main/scala/Fir.scala:8:14]
  input  [3:0] io_consts_0,	// @[src/main/scala/Fir.scala:8:14]
  input  [3:0] io_consts_1,	// @[src/main/scala/Fir.scala:8:14]
  input  [3:0] io_consts_2,	// @[src/main/scala/Fir.scala:8:14]
  input  [3:0] io_consts_3	// @[src/main/scala/Fir.scala:8:14]
);

  reg [3:0] taps_1;	// @[src/main/scala/Fir.scala:16:66]
  reg [3:0] taps_2;	// @[src/main/scala/Fir.scala:16:66]
  reg [3:0] taps_3;	// @[src/main/scala/Fir.scala:16:66]
  always @(posedge clock) begin	// @[src/main/scala/Fir.scala:7:7]
    if (reset) begin	// @[src/main/scala/Fir.scala:7:7]
      taps_1 <= 4'h0;	// @[src/main/scala/Fir.scala:16:66]
      taps_2 <= 4'h0;	// @[src/main/scala/Fir.scala:16:66]
      taps_3 <= 4'h0;	// @[src/main/scala/Fir.scala:16:66]
    end
    else if (io_valid) begin	// @[src/main/scala/Fir.scala:8:14]
      taps_1 <= io_in;	// @[src/main/scala/Fir.scala:16:66]
      taps_2 <= taps_1;	// @[src/main/scala/Fir.scala:16:66]
      taps_3 <= taps_2;	// @[src/main/scala/Fir.scala:16:66]
    end
  end // always @(posedge)
  assign io_out = io_in * io_consts_0 + taps_1 * io_consts_1 + taps_2 * io_consts_2 + taps_3 * io_consts_3;	// @[src/main/scala/Fir.scala:7:7, :16:66, :19:{56,71}]
endmodule

